const stages=[
 {name:'The Song',kicker:'STAGE 01',status:'READY'},
 {name:'Reveal the World',kicker:'STAGE 02',status:'GENERATING'},
 {name:'World Assets',kicker:'STAGE 03',status:'GENERATING'},
 {name:'Storyboard',kicker:'STAGE 04',status:'GENERATING'},
 {name:'Scene Direction',kicker:'STAGE 05',status:'GENERATING'},
 {name:'Visual Scenes',kicker:'STAGE 06',status:'GENERATING'},
 {name:'Motion & Edit',kicker:'STAGE 07',status:'PREVIEW'},
 {name:'The Pitch',kicker:'STAGE 08',status:'PARTNERSHIP'}
];
let current=0, approved={};
const $=s=>document.querySelector(s);
function renderNav(){ $('#stageNav').innerHTML=stages.map((s,i)=>`<div class="stage-item ${i===current?'active':''} ${i<current?'done':''}">${String(i+1).padStart(2,'0')} &nbsp; ${s.name}</div>`).join(''); $('#progressText').textContent=`${current+1} / ${stages.length}`; }
function setStage(i){current=Math.max(0,Math.min(stages.length-1,i));renderNav();render();}
function render(){
 const s=stages[current];$('#stageKicker').textContent=s.kicker;$('#stageTitle').textContent=s.name;$('#stageStatus').textContent=s.status;$('#backBtn').style.visibility=current?'visible':'hidden';$('#nextBtn').textContent=current===stages.length-1?'Restart demo →':'Continue →';
 const views=[song,world,assets,storyboard,prompts,scenes,motion,pitch];$('#stageContent').innerHTML=views[current]();
 if(current===1||current===2||current===3||current===4||current===5){$('#stageContent').querySelectorAll('.reveal').forEach((e,n)=>setTimeout(()=>e.classList.remove('reveal'),150+n*120));}
}
function song(){return `<div class="song-card card"><div class="art">BV</div><div class="meta"><span class="meta-label">DEMO TRACK</span><h3>Midnight Static</h3><p>Original demonstration track • 03:42</p><div class="input-row"><span class="meta-label">CREATIVE DIRECTION</span><div class="fake-input">Neon-noir • emotional • cinematic • industrial pulse</div></div><div class="input-row"><span class="meta-label">LYRICS</span><div class="fake-input">A city breathing electricity...<br>Every shadow knows my name...<br>We disappear into the static.</div></div></div></div><div class="card" style="margin-top:14px"><span class="meta-label">THE IDEA</span><p>BeatVision does not ask the creator to become a prompt engineer. The creator supplies the song and intent. The system builds the visual language.</p></div>`}
function world(){return `<div class="card reveal"><div style="display:flex;justify-content:space-between"><div><span class="meta-label">VISUAL WORLD REPORT</span><h3>NEON AFTERIMAGE</h3></div><span class="tag">DEMO OUTPUT</span></div><p>A rain-slick midnight city where memory behaves like electricity. Human emotion appears as colored interference across glass, skin and architecture. The camera feels intimate even when the world is enormous.</p><div class="tag-row"><span class="tag">NEON NOIR</span><span class="tag">RAIN</span><span class="tag">CHROMATIC GHOSTS</span><span class="tag">35MM GRAIN</span><span class="tag">HIGH CONTRAST</span></div></div><div class="report-grid" style="margin-top:14px"><div class="card reveal"><span class="meta-label">EMOTIONAL ARC</span><p>Isolation → pursuit → confrontation → release</p></div><div class="card reveal"><span class="meta-label">VISUAL RULE</span><p>Keep the protagonist warm against a cold, electrically alive city.</p></div></div><div class="card" style="margin-top:14px;border-color:#4a3a25"><span class="meta-label">APPROVAL GATE</span><p>In the full product, this is where the creator confirms: <b>“Yes, that’s my world.”</b></p></div>`}
function assets(){return `<div class="assets-grid"><div class="card reveal asset"><div class="asset-img"></div><span class="meta-label">01 • WORLD STYLE BIBLE</span><h3>Neon Afterimage</h3><p>Palette, texture, lens language, lighting and continuity rules.</p></div><div class="card reveal asset"><div class="asset-img"></div><span class="meta-label">02 • CHARACTER</span><h3>The Runner</h3><p>Consistent silhouette, wardrobe, age, expression and visual identity.</p></div><div class="card reveal asset"><div class="asset-img"></div><span class="meta-label">03 • ENVIRONMENT</span><h3>Electric City</h3><p>Rain, glass towers, underpasses and luminous signage.</p></div></div><div class="card" style="margin-top:14px"><span class="meta-label">CONSISTENCY ENGINE</span><p>These assets become shared creative constraints for every downstream scene, giving providers a structured target instead of isolated image prompts.</p></div>`}
function storyboard(){const beats=['Signal','The City Wakes','Running Blind','The Memory','Crossing','Confrontation','Breakthrough','Afterimage'];return `<div class="story-list">${beats.map((b,i)=>`<div class="story-row reveal"><b>0${i+1}</b><span>${b}</span><small>${['Intro','Verse','Verse','Hook','Bridge','Hook','Finale','Outro'][i]}</small></div>`).join('')}</div><div class="card" style="margin-top:14px"><span class="meta-label">STORY LOGIC</span><p>Eight production-ready beats give a video model clear temporal structure while preserving one visual world.</p></div>`}
function prompts(){return `<div class="card reveal"><span class="meta-label">SCENE PROMPT SYSTEM</span><h3>One world. Eight directions.</h3><p>Every scene prompt inherits the approved world bible, character continuity, environment continuity and musical beat. This is the bridge between creative intent and provider APIs.</p><div class="story-list"><div class="story-row"><b>SCENE 01</b><span>Close tracking shot through rain-soaked neon</span><small>CAMERA</small></div><div class="story-row"><b>SCENE 04</b><span>Memory fractures across reflective glass</span><small>EMOTION</small></div><div class="story-row"><b>SCENE 07</b><span>Warm figure emerges from electrical storm</span><small>PAYOFF</small></div></div></div>`}
function scenes(){return `<div class="scene-grid">${Array.from({length:8},(_,i)=>`<div class="card scene reveal"><div class="scene-thumb">SCENE ${String(i+1).padStart(2,'0')}</div><div class="scene-info"><b>${['SIGNAL','CITY','RUN','MEMORY','CROSSING','FIGHT','BREAKTHROUGH','AFTERIMAGE'][i]}</b><p>Provider-ready visual frame</p></div></div>`).join('')}</div><div class="card" style="margin-top:14px"><span class="meta-label">REFERENCE PHOTO SUPPORT</span><p>Creator reference images can be assigned to individual scenes. The architecture tracks reference IDs separately from prompts so providers can later receive actual image inputs where supported.</p></div>`}
function motion(){return `<div class="motion"><div><div class="timeline"><span class="meta-label">MOTION TIMELINE • 03:42</span><div class="track"></div><div class="track"></div><div class="track"></div><div class="playhead"></div></div><div class="card" style="margin-top:14px"><span class="meta-label">VIDEO PROVIDER HANDOFF</span><p>Approved scene images become source frames. A video provider supplies motion, camera movement and temporal consistency. BeatVision owns the creative sequence and final edit logic.</p></div></div><div class="card"><span class="meta-label">EXPORT PLAN</span><h3>Music Video</h3><p>8 scenes • beat-synced transitions • final audio • 16:9 master</p><div class="tag-row"><span class="tag">1080P</span><span class="tag">24 FPS</span><span class="tag">H.264</span></div><button class="primary-btn" style="margin-top:20px" onclick="alert('Presentation prototype: final rendering is the provider-powered stage.')">Preview Render</button></div></div>`}
function pitch(){return `<div class="card" style="padding:34px"><span class="meta-label">BEATVISION × YOUR TECHNOLOGY</span><h3 style="font-size:34px;margin:12px 0">The product is the creative pipeline. Your API can power the engine.</h3><p style="max-width:720px">BeatVision is built to orchestrate specialized AI capabilities behind one creator experience. We are seeking providers willing to support the prototype with API credits, startup programs, infrastructure or strategic partnership.</p><div class="provider-grid"><article><span class="provider-num">LANGUAGE</span><h3>World + Story</h3><p>Structured interpretation of lyrics and intent.</p></article><article><span class="provider-num">IMAGE</span><h3>Visual Assets</h3><p>Characters, environments and scenes.</p></article><article><span class="provider-num">VIDEO</span><h3>Motion</h3><p>Animation, temporal consistency and render.</p></article><article><span class="provider-num">INFRA</span><h3>Scale</h3><p>Jobs, storage, compute and delivery.</p></article></div></div>`}
$('#startDemo').onclick=()=>{$('#hero').classList.add('hidden');$('#workspace').classList.remove('hidden');setStage(0);window.scrollTo(0,0)};
$('#watchFlow').onclick=()=>document.querySelector('#workspace')?.scrollIntoView({behavior:'smooth'});
$('#nextBtn').onclick=()=>current===stages.length-1?setStage(0):setStage(current+1);
$('#backBtn').onclick=()=>setStage(current-1);
$('#providerBtn').onclick=()=>$('#providerPanel').classList.remove('hidden');
$('#closeProvider').onclick=()=>$('#providerPanel').classList.add('hidden');
renderNav();
